export const generalCategory = {
  Lo: 'Letter, Other',
  Mn: 'Mark, Nonspacing',
  Mc: 'Mark, Spacing Combining',
  Nd: 'Number, Decimal Digit',
  Po: 'Punctuation, Other',
  No: 'Number, Other',
  So: 'Symbol, Other',
  Pd: 'Punctuation, Dash',
  Zs: 'Separator, Space',
  Lm: 'Letter, Modifier',
  Pi: 'Punctuation, Initial quote',
  Pf: 'Punctuation, Final quote',
  Zl: 'Separator, Line',
  Zp: 'Separator, Paragraph',
  Pc: 'Punctuation, Connector',
  Sm: 'Symbol, Math',
  Ps: 'Punctuation, Open',
  Pe: 'Punctuation, Close',
  Cf: 'Other, Format',
  Lu: 'Letter, Uppercase',
  Ll: 'Letter, Lowercase',
  Nl: 'Number, Letter',
  Cc: 'Other, Control',
  Sc: 'Symbol, Currency',
  Sk: 'Symbol, Modifier',
  Lt: 'Letter, Titlecase',
  Me: 'Mark, Enclosing',
} as const

export const generalCategoryShort = [
  'Lo',
  'Mn',
  'Mc',
  'Nd',
  'Po',
  'No',
  'So',
  'Pd',
  'Zs',
  'Lm',
  'Pi',
  'Pf',
  'Zl',
  'Zp',
  'Pc',
  'Sm',
  'Ps',
  'Pe',
  'Cf',
  'Lu',
  'Ll',
  'Nl',
  'Cc',
  'Sc',
  'Sk',
  'Lt',
  'Me',
] as const

export type GeneralCategoryShort = keyof typeof generalCategory
export type GeneralCategory = (typeof generalCategory)[GeneralCategoryShort]

export const Blocks = [
  'ASCII',
  'Latin_1_Sup',
  'Latin_Ext_A',
  'Latin_Ext_B',
  'IPA_Ext',
  'Modifier_Letters',
  'Diacriticals',
  'Greek',
  'Cyrillic',
  'Cyrillic_Sup',
  'Armenian',
  'Hebrew',
  'Arabic',
  'Syriac',
  'Arabic_Sup',
  'Thaana',
  'NKo',
  'Samaritan',
  'Mandaic',
  'Syriac_Sup',
  'Arabic_Ext_B',
  'Arabic_Ext_A',
  'Devanagari',
  'Bengali',
  'Gurmukhi',
  'Gujarati',
  'Oriya',
  'Tamil',
  'Telugu',
  'Kannada',
  'Malayalam',
  'Sinhala',
  'Thai',
  'Lao',
  'Tibetan',
  'Myanmar',
  'Georgian',
  'Jamo',
  'Ethiopic',
  'Ethiopic_Sup',
  'Cherokee',
  'UCAS',
  'Ogham',
  'Runic',
  'Tagalog',
  'Hanunoo',
  'Buhid',
  'Tagbanwa',
  'Khmer',
  'Mongolian',
  'UCAS_Ext',
  'Limbu',
  'Tai_Le',
  'New_Tai_Lue',
  'Khmer_Symbols',
  'Buginese',
  'Tai_Tham',
  'Diacriticals_Ext',
  'Balinese',
  'Sundanese',
  'Batak',
  'Lepcha',
  'Ol_Chiki',
  'Cyrillic_Ext_C',
  'Georgian_Ext',
  'Sundanese_Sup',
  'Vedic_Ext',
  'Phonetic_Ext',
  'Phonetic_Ext_Sup',
  'Diacriticals_Sup',
  'Latin_Ext_Additional',
  'Greek_Ext',
  'Punctuation',
  'Super_And_Sub',
  'Currency_Symbols',
  'Diacriticals_For_Symbols',
  'Letterlike_Symbols',
  'Number_Forms',
  'Arrows',
  'Math_Operators',
  'Misc_Technical',
  'Control_Pictures',
  'OCR',
  'Enclosed_Alphanum',
  'Box_Drawing',
  'Block_Elements',
  'Geometric_Shapes',
  'Misc_Symbols',
  'Dingbats',
  'Misc_Math_Symbols_A',
  'Sup_Arrows_A',
  'Braille',
  'Sup_Arrows_B',
  'Misc_Math_Symbols_B',
  'Sup_Math_Operators',
  'Misc_Arrows',
  'Glagolitic',
  'Latin_Ext_C',
  'Coptic',
  'Georgian_Sup',
  'Tifinagh',
  'Ethiopic_Ext',
  'Cyrillic_Ext_A',
  'Sup_Punctuation',
  'CJK_Radicals_Sup',
  'Kangxi',
  'IDC',
  'CJK_Symbols',
  'Hiragana',
  'Katakana',
  'Bopomofo',
  'Compat_Jamo',
  'Kanbun',
  'Bopomofo_Ext',
  'CJK_Strokes',
  'Katakana_Ext',
  'Enclosed_CJK',
  'CJK_Compat',
  'CJK_Ext_A',
  'Yijing',
  'CJK',
  'Yi_Syllables',
  'Yi_Radicals',
  'Lisu',
  'Vai',
  'Cyrillic_Ext_B',
  'Bamum',
  'Modifier_Tone_Letters',
  'Latin_Ext_D',
  'Syloti_Nagri',
  'Indic_Number_Forms',
  'Phags_Pa',
  'Saurashtra',
  'Devanagari_Ext',
  'Kayah_Li',
  'Rejang',
  'Jamo_Ext_A',
  'Javanese',
  'Myanmar_Ext_B',
  'Cham',
  'Myanmar_Ext_A',
  'Tai_Viet',
  'Meetei_Mayek_Ext',
  'Ethiopic_Ext_A',
  'Latin_Ext_E',
  'Cherokee_Sup',
  'Meetei_Mayek',
  'Hangul',
  'Jamo_Ext_B',
  'CJK_Compat_Ideographs',
  'Alphabetic_PF',
  'Arabic_PF_A',
  'VS',
  'Vertical_Forms',
  'Half_Marks',
  'CJK_Compat_Forms',
  'Small_Forms',
  'Arabic_PF_B',
  'Half_And_Full_Forms',
  'Specials',
  'Linear_B_Syllabary',
  'Linear_B_Ideograms',
  'Aegean_Numbers',
  'Ancient_Greek_Numbers',
  'Ancient_Symbols',
  'Phaistos',
  'Lycian',
  'Carian',
  'Coptic_Epact_Numbers',
  'Old_Italic',
  'Gothic',
  'Old_Permic',
  'Ugaritic',
  'Old_Persian',
  'Deseret',
  'Shavian',
  'Osmanya',
  'Osage',
  'Elbasan',
  'Caucasian_Albanian',
  'Vithkuqi',
  'Linear_A',
  'Latin_Ext_F',
  'Cypriot_Syllabary',
  'Imperial_Aramaic',
  'Palmyrene',
  'Nabataean',
  'Hatran',
  'Phoenician',
  'Lydian',
  'Meroitic_Hieroglyphs',
  'Meroitic_Cursive',
  'Kharoshthi',
  'Old_South_Arabian',
  'Old_North_Arabian',
  'Manichaean',
  'Avestan',
  'Inscriptional_Parthian',
  'Inscriptional_Pahlavi',
  'Psalter_Pahlavi',
  'Old_Turkic',
  'Old_Hungarian',
  'Hanifi_Rohingya',
  'Rumi',
  'Yezidi',
  'Arabic_Ext_C',
  'Old_Sogdian',
  'Sogdian',
  'Old_Uyghur',
  'Chorasmian',
  'Elymaic',
  'Brahmi',
  'Kaithi',
  'Sora_Sompeng',
  'Chakma',
  'Mahajani',
  'Sharada',
  'Sinhala_Archaic_Numbers',
  'Khojki',
  'Multani',
  'Khudawadi',
  'Grantha',
  'Newa',
  'Tirhuta',
  'Siddham',
  'Modi',
  'Mongolian_Sup',
  'Takri',
  'Ahom',
  'Dogra',
  'Warang_Citi',
  'Dives_Akuru',
  'Nandinagari',
  'Zanabazar_Square',
  'Soyombo',
  'UCAS_Ext_A',
  'Pau_Cin_Hau',
  'Devanagari_Ext_A',
  'Bhaiksuki',
  'Marchen',
  'Masaram_Gondi',
  'Gunjala_Gondi',
  'Makasar',
  'Kawi',
  'Lisu_Sup',
  'Tamil_Sup',
  'Cuneiform',
  'Cuneiform_Numbers',
  'Early_Dynastic_Cuneiform',
  'Cypro_Minoan',
  'Egyptian_Hieroglyphs',
  'Egyptian_Hieroglyph_Format_Controls',
  'Anatolian_Hieroglyphs',
  'Bamum_Sup',
  'Mro',
  'Tangsa',
  'Bassa_Vah',
  'Pahawh_Hmong',
  'Medefaidrin',
  'Miao',
  'Ideographic_Symbols',
  'Tangut',
  'Tangut_Components',
  'Khitan_Small_Script',
  'Tangut_Sup',
  'Kana_Ext_B',
  'Kana_Sup',
  'Kana_Ext_A',
  'Small_Kana_Ext',
  'Nushu',
  'Duployan',
  'Shorthand_Format_Controls',
  'Znamenny_Music',
  'Byzantine_Music',
  'Music',
  'Ancient_Greek_Music',
  'Kaktovik_Numerals',
  'Mayan_Numerals',
  'Tai_Xuan_Jing',
  'Counting_Rod',
  'Math_Alphanum',
  'Sutton_SignWriting',
  'Latin_Ext_G',
  'Glagolitic_Sup',
  'Cyrillic_Ext_D',
  'Nyiakeng_Puachue_Hmong',
  'Toto',
  'Wancho',
  'Nag_Mundari',
  'Ethiopic_Ext_B',
  'Mende_Kikakui',
  'Adlam',
  'Indic_Siyaq_Numbers',
  'Ottoman_Siyaq_Numbers',
  'Arabic_Math',
  'Mahjong',
  'Domino',
  'Playing_Cards',
  'Enclosed_Alphanum_Sup',
  'Enclosed_Ideographic_Sup',
  'Misc_Pictographs',
  'Emoticons',
  'Ornamental_Dingbats',
  'Transport_And_Map',
  'Alchemical',
  'Geometric_Shapes_Ext',
  'Sup_Arrows_C',
  'Sup_Symbols_And_Pictographs',
  'Chess_Symbols',
  'Symbols_And_Pictographs_Ext_A',
  'Symbols_For_Legacy_Computing',
  'CJK_Ext_B',
  'CJK_Ext_C',
  'CJK_Ext_D',
  'CJK_Ext_E',
  'CJK_Ext_F',
  'CJK_Ext_I',
  'CJK_Compat_Ideographs_Sup',
  'CJK_Ext_G',
  'CJK_Ext_H',
  'Tags',
  'VS_Sup',
] as const
export type Block = (typeof Blocks)[number]
